# -*- coding: utf-8 -*-
"""kras_missense

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgnkoqcTf5iUAXqnNvNnEn5da1j8PE7K
"""

import pandas as pd
import numpy as np
import re # Metin parçalama ustası (regular expressions)

# Ham veriyi yükle ve düzelt
df = pd.read_csv("mutations.txt", sep='\t')

# İlk filtre: Sağlıklıları (WT) ve boşları çöpe at
df_mutant = df[df['KRAS'] != 'WT'].copy()
df_mutant = df_mutant.dropna(subset=['KRAS'])

# HASTA BARKODU DÜZELTME

# Sample ID genelde "TCGA-AR-A1AQ-01" gibidir. Sondaki "-01" gibi tümör/doku tiplerini atıp hastanın saf kimlik numarasını (ilk 12 karakteri) çıkarıyoruz.
df_mutant['Saf_Hasta_ID'] = df_mutant['SAMPLE_ID'].apply(lambda x: str(x) [:12])

# REGEX İLE GENETİK ŞİFREYİ PARÇALAMA

# "R273H" VEYA "C275Lfs*67" gibi kodların içindeki rakamı çekip alıyoruz
def pozisyon_bul(mutasyon_kodu):
  rakamlar = re.findall(r'\d+', str(mutasyon_kodu))
  if rakamlar:
    return int(rakamlar[0])
  return np.nan

df_mutant['Aminoasit_Poz'] = df_mutant['KRAS'].apply(pozisyon_bul)

# BİYOLOJİK SINIFLANDIRMA VE HASAR TİPİ

def hasar_tipi(kod):
  kod = str(kod).lower()
  if '*' in kod or 'fs' in kod or 'del' in kod:
    return 'Yıkıcı/Kopma (Truncating)'
  elif 'splice' in kod:
    return 'Kıvrılma (Splice)'
  else:
    return 'Yer değiştirme (Missense)'

df_mutant['Hasar_Tipi'] = df_mutant['KRAS'].apply(hasar_tipi)

def bolge_etiketle(poz):
  if pd.isna(poz):
    return 'Bilinmiyor'
  elif poz in [12, 13, 61]:
    return 'KRİTİK: GTP Bağlanma Cebi (Hotspot)'
  else:
    return 'Dış Bölge / Nadir Mutasyon'

df_mutant['Protein_Bölgesi'] = df_mutant['Aminoasit_Poz'].apply(bolge_etiketle)

# SONUÇ TABLO HAZIRLAMA VE RAPORLAMA

# Gereksiz sütunları atıp sadece oluşturduğumuz şık sütunları tutuyoruz
df_final = df_mutant[['Saf_Hasta_ID', 'KRAS', 'Aminoasit_Poz', 'Hasar_Tipi', 'Protein_Bölgesi']]

print("=== GELİŞMİŞ VERİ MÜHENDİSLİĞİ RAPORU ===")
print(f"Toplmal Mutant Hasta Sayısı: {len(df_final)}")
print("\n--- Mutasyonların Hasar Tiplerine Göre Dağılımı ---")
print(df_final['Hasar_Tipi'].value_counts())
print("\n--- Hasarın Proteindeki Konumu ---")
print(df_final['Protein_Bölgesi'].value_counts())

# İlk 15 satırı göster
df_final.head(15)

# df_final.to_csv("tum_kras_verisi.csv", index=False)

df_final.to_excel("tum_kras_verisi.xlsx", index=False)

